// 원격 서명 화면 안내 문안 사전 — 입주자가 읽는 문장의 정본(2026-09-06, checklist 8번).
//
// 왜 있나. 서명 안내가 한국어 + 영어 고정 병기였는데, 실측(거주·예약 47명)에서 베트남·방글라데시·
// 러시아권·일본·중국 국적이 13명이다. "외국인이라고 모두 영어를 잘하는 건 아니야"(운영자).
//
// 구조 규칙 셋.
//   1. 언어 코드는 링크 발급 때 templateSnapshot.signLang 으로 **박제**된다. 발급 후 무엇을
//      바꿔도 그 링크의 안내 언어는 안 바뀐다(413호 표기 사고와 같은 클래스 방지). 이어받기는
//      스냅샷 통째 승계라 코드 0줄로 따라온다.
//   2. 사전은 Record<SignLang, Record<SignKey, string>> **전량 선언**이다. Partial 금지 —
//      키 하나가 빠지면 tsc 가 컴파일을 막는다. 그것이 누락 키 감지망이다.
//   3. 화면은 한국어 정본 줄 + 선택 언어 부속 줄 병기다(bi). 한국어를 고르면 부속 줄이 영어다 —
//      부속 줄은 원격이면 언제나 선다(check-sign-screen-n ⓐ). 그리고 bi 결과에 한글이 항상
//      있어야 humanError(한글 없는 문자열을 폴백으로 갈아치운다)를 안전하게 지난다.
//
// 문안 규칙. 숫자는 모든 언어에서 아라비아 숫자 그대로 쓴다(복수형 규칙을 만들지 않는다 —
// 아라비아 숫자가 가장 강한 무텍스트 신호라는 기존 판정 그대로). 보간은 {n} {total} {left}
// {title} {biz} 단순 치환. 계약서·동의서 본문(법적 문안)은 이 사전의 대상이 아니다.

import { isKoreanNationality } from '@/lib/documentName'

export type SignLang = 'ko' | 'en' | 'vi' | 'bn' | 'ru' | 'ja' | 'zh' | 'zht'
export const SIGN_LANGS: readonly SignLang[] = ['ko', 'en', 'vi', 'bn', 'ru', 'ja', 'zh', 'zht']

/** 발급 피커 라벨 — 한국어 이름 + 그 언어 자기 이름. */
export const SIGN_LANG_LABEL: Record<SignLang, string> = {
  ko: '한국어',
  en: '영어 English',
  vi: '베트남어 Tiếng Việt',
  bn: '벵골어(방글라데시) বাংলা',
  ru: '러시아어 Русский',
  ja: '일본어 日本語',
  zh: '중국어(간체) 简体中文',
  zht: '중국어(번체) 繁體中文',
}

/** 화이트리스트 파서 — 스냅샷에서 읽은 값은 외부 데이터다. */
export function asSignLang(v: unknown): SignLang | undefined {
  return typeof v === 'string' && (SIGN_LANGS as readonly string[]).includes(v) ? (v as SignLang) : undefined
}

/**
 * 국적의 기본 안내 언어. **기본값일 뿐이다** — 발급 피커에서 운영자가 바꿀 수 있다.
 * (김명화님처럼 국적은 중국이어도 한국어가 편한 분이 있다. 운영자 지시 2026-09-06.)
 *
 * 카자흐스탄·우즈베키스탄은 러시아어가 민족 간 공용어라 ru 로 둔다(자국어 사전이 생기면
 * 이 줄만 고친다). 레바논 등 매핑에 없는 외국 국적은 en 폴백 — 아랍어는 RTL 조판 검증
 * 비용 대비 수혜자 1명이라 이번에 열지 않았다(설계 2026-09-06).
 */
export function signLangForNationality(nationality: string | null | undefined): SignLang {
  if (isKoreanNationality(nationality)) return 'ko'
  const v = (nationality ?? '').trim()
  if (v === '베트남') return 'vi'
  if (v === '방글라데시') return 'bn'
  if (v === '러시아' || v === '카자흐스탄' || v === '우즈베키스탄' || v === '벨라루스' || v === '키르기스스탄') return 'ru'
  if (v === '일본') return 'ja'
  if (v === '중국') return 'zh'
  if (v === '대만' || v === '홍콩') return 'zht'
  return 'en'
}

// ── 한국어 정본 — 현행 화면 문자열 그대로 옮겼다(문안 개정은 이 작업의 범위가 아니다) ──
const KO = {
  'gate.title': '입실 계약서 확인',
  'gate.hint': '본인 확인을 위해 생년월일을 입력해 주세요. 확인 후 계약 내용을 열람하고 서명할 수 있습니다.',
  'gate.birthLabel': '생년월일',
  'gate.placeholder': '예: 19700928',
  'gate.submit': '확인',
  'gate.submitting': '확인 중…',
  'gate.netFail': '확인에 실패했습니다. 잠시 후 다시 시도해 주세요.',
  'gate.privacy': '입력하신 생년월일은 본인 확인에만 쓰이고 따로 저장하지 않습니다. 계약서에 적힌 정보는 계약 체결과 이행을 위해 영업장이 보관합니다.',
  'inactive.title': '사용할 수 없는 링크',
  'inactive.body': '링크가 만료되었거나 사용할 수 없습니다. 관리자에게 다시 요청해 주세요.',
  'submitted.title': '계약서가 제출되었습니다',
  'submitted.body': '이미 제출이 완료되어 더 이상 열 수 없습니다. 이 창은 닫으셔도 됩니다.',
  'err.locked': '입력 오류가 {n}회가 되어 링크가 잠겼습니다. 관리자에게 다시 요청해 주세요.',
  'err.birthMismatch': '생년월일이 일치하지 않습니다. 남은 시도 {n}회.',
  'err.cookieExpired': '본인 확인이 만료되었습니다. 페이지를 새로고침해 생년월일을 다시 입력해 주세요.',
  'err.badRequest': '잘못된 요청입니다.',
  'err.badImage': '서명 이미지가 올바르지 않습니다.',
  'err.imageTooLarge': '서명 이미지가 너무 큽니다. 다시 서명해 주세요.',
  'err.disposalOff': '이 영업장은 잔여 소지품 동의서를 사용하지 않습니다.',
  'err.saveFail': '서명 저장에 실패했습니다. 잠시 후 다시 시도해 주세요.',
  'err.signFirst': '먼저 서명을 완료해 주세요.',
  'err.disposalLeft': '동의서 서명이 아직 없습니다. 동의서 서명란에 서명한 뒤 제출해 주세요.',
  'err.docLeft': "'{title}' 서명이 아직 없습니다. 그 서류의 서명란에 서명한 뒤 제출해 주세요.",
  'err.submitFail': '제출에 실패했습니다. 잠시 후 다시 시도해 주세요.',
  'bar.readAndSign': '계약 내용을 확인한 뒤 하단 서명란을 눌러 서명해 주세요.',
  'bar.allSaved': '서명이 모두 저장되었습니다. 아래 버튼으로 제출해 주세요.',
  'cta.sign': '여기를 눌러 서명',
  'progress.done1': '서명이 완료됐습니다.',
  'progress.doneN': '서명 {total} / {total} · 모두 완료됐습니다.',
  'progress.none1': '서명해 주세요.',
  'progress.noneN': '서명 0 / {total} · {total}곳에 서명해 주세요.',
  'progress.some': '서명 {n} / {total} · {left}곳 더 서명해 주세요.',
  'cta.submit': '제출하기',
  'cta.submitting': '제출 중…',
  'pill.allDone': '모든 서명이 완료됐습니다',
  'pad.titleContract': '입실자 서명',
  'pad.titleDoc': '{title} 서명',
  'pad.subRemote': '아래 영역에 서명해주세요. 확인을 누르면 {title} 서명이 적용됩니다.',
  'pad.clear': '지우기',
  'pad.cancel': '취소',
  'pad.confirm': '확인',
  'pad.saving': '저장 중…',
  'pad.close': '닫기',
  'pad.errEmpty': '서명을 입력해주세요.',
  'pad.errShort': '서명이 너무 짧습니다. 성함을 이어서 그려 주세요.',
  'pad.errComm': '서명 저장 중 통신 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.',
  'toast.signedContract': '서명이 입력되었습니다',
  'toast.signedDoc': '{title} 서명이 입력되었습니다',
  'remain.title1': '서명 {n} / {total} · {title}가 남았습니다',
  'remain.titleN': '서명 {n} / {total} · {left}장 남았습니다',
  'remain.msg': '이 링크에는 서류가 {total}장 있습니다. 남은 {left}장에 서명해야 제출할 수 있습니다.',
  'remain.go': '서명하러 가기',
  'submit.confirmTitle': '계약서를 제출할까요?',
  'submit.confirmMsg': '제출하면 이 링크는 닫힙니다. 다시 열거나 수정할 수 없습니다.\n서명을 고치려면 제출 전에 다시 서명해 주세요.',
  'submit.confirmLabel': '제출',
  'submit.errComm': '제출 중 통신 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.',
  'done.title': '계약서가 제출되었습니다',
  'done.body': '이 링크는 닫혔습니다. 다시 열 수 없습니다. 이 창은 닫으셔도 됩니다.',
  'native.label': '본국 표기 이름',
  'native.required': '본국 표기 이름을 적어 주세요. 계약서 성명 옆에 함께 실립니다.',
  'native.hint': '여권이나 본국 서류에 적힌 표기를 그대로 적어 주세요.',
  'doc.contract': '입실계약서',
  'doc.disposal': '동의서',
  'doc.generic': '서류',
  'common.cancel': '취소',
  'sms.body': '[{biz}] 입실 계약서입니다. 아래 링크에서 계약 내용을 확인하고 서명해 주세요. 확인을 위해 본인 생년월일 입력이 필요합니다. 제출하시면 링크는 닫히고, 제출 전이라도 24시간 뒤 만료됩니다.',
} as const

export type SignKey = keyof typeof KO

const EN: Record<SignKey, string> = {
  'gate.title': 'Room Contract Verification',
  'gate.hint': 'Enter your date of birth to verify your identity. After verification you can read and sign the contract.',
  'gate.birthLabel': 'Date of birth',
  'gate.placeholder': 'e.g. 19700928',
  'gate.submit': 'Confirm',
  'gate.submitting': 'Checking…',
  'gate.netFail': 'Verification failed. Please try again in a moment.',
  'gate.privacy': 'Your date of birth is used only for identity verification and is not stored. Information in the contract is kept by the business to conclude and carry out the contract.',
  'inactive.title': 'Link unavailable',
  'inactive.body': 'This link has expired or cannot be used. Please ask the manager to send it again.',
  'submitted.title': 'Contract submitted',
  'submitted.body': 'It has already been submitted and can no longer be opened. You may close this window.',
  'err.locked': 'The link is locked after {n} failed attempts. Please ask the manager to send it again.',
  'err.birthMismatch': 'Date of birth does not match. {n} attempts left.',
  'err.cookieExpired': 'Identity verification has expired. Refresh the page and enter your date of birth again.',
  'err.badRequest': 'Invalid request.',
  'err.badImage': 'The signature image is not valid.',
  'err.imageTooLarge': 'The signature image is too large. Please sign again.',
  'err.disposalOff': 'This business does not use the belongings disposal consent form.',
  'err.saveFail': 'Failed to save the signature. Please try again in a moment.',
  'err.signFirst': 'Please complete your signature first.',
  'err.disposalLeft': 'The consent form is not signed yet. Sign it before submitting.',
  'err.docLeft': "'{title}' is not signed yet. Sign that document before submitting.",
  'err.submitFail': 'Submission failed. Please try again in a moment.',
  'bar.readAndSign': 'Read the contract, then tap the signature box at the bottom to sign.',
  'bar.allSaved': 'All signatures are saved. Submit with the button below.',
  'cta.sign': 'Tap here to sign',
  'progress.done1': 'Signed. Thank you.',
  'progress.doneN': '{total} / {total} signed. All done.',
  'progress.none1': 'Please sign.',
  'progress.noneN': '0 / {total} signed. Please sign all {total}.',
  'progress.some': '{n} / {total} signed. {left} left.',
  'cta.submit': 'Submit',
  'cta.submitting': 'Submitting…',
  'pill.allDone': 'All signatures completed',
  'pad.titleContract': 'Tenant signature',
  'pad.titleDoc': '{title} signature',
  'pad.subRemote': 'Sign in the area below. Tap Confirm to apply your signature to {title}.',
  'pad.clear': 'Clear',
  'pad.cancel': 'Cancel',
  'pad.confirm': 'Confirm',
  'pad.saving': 'Saving…',
  'pad.close': 'Close',
  'pad.errEmpty': 'Please sign first.',
  'pad.errShort': 'Signature too short. Please draw your full signature.',
  'pad.errComm': 'A network error occurred while saving. Please try again in a moment.',
  'toast.signedContract': 'Signature added',
  'toast.signedDoc': '{title} signature added',
  'remain.title1': '{n} / {total} signed. {title} is left',
  'remain.titleN': '{n} / {total} signed. {left} documents left',
  'remain.msg': 'This link has {total} documents. Sign the remaining {left} to submit.',
  'remain.go': 'Go to signature',
  'submit.confirmTitle': 'Submit the contract?',
  'submit.confirmMsg': 'After submitting, this link closes and cannot be reopened or edited.\nTo change a signature, sign again before submitting.',
  'submit.confirmLabel': 'Submit',
  'submit.errComm': 'A network error occurred while submitting. Please try again in a moment.',
  'done.title': 'Contract submitted',
  'done.body': 'This link is now closed and cannot be reopened. You may close this window.',
  'native.label': 'Name in your native script',
  'native.required': 'Please write your name in your native script. It will appear next to your name on the contract.',
  'native.hint': 'Write your name exactly as in your passport or home-country documents.',
  'doc.contract': 'Room contract',
  'doc.disposal': 'Consent form',
  'doc.generic': 'Document',
  'common.cancel': 'Cancel',
  'sms.body': '[{biz}] Your room contract. Open the link below to read and sign it. You will need your date of birth for verification. The link closes after submission and expires in 24 hours.',
}

const VI: Record<SignKey, string> = {
  'gate.title': 'Xác nhận hợp đồng thuê phòng',
  'gate.hint': 'Nhập ngày sinh của bạn để xác minh danh tính. Sau khi xác minh, bạn có thể đọc và ký hợp đồng.',
  'gate.birthLabel': 'Ngày sinh',
  'gate.placeholder': 'Ví dụ: 19700928',
  'gate.submit': 'Xác nhận',
  'gate.submitting': 'Đang kiểm tra…',
  'gate.netFail': 'Xác minh thất bại. Vui lòng thử lại sau giây lát.',
  'gate.privacy': 'Ngày sinh của bạn chỉ dùng để xác minh danh tính và không được lưu lại. Thông tin trong hợp đồng do cơ sở lưu giữ để ký kết và thực hiện hợp đồng.',
  'inactive.title': 'Liên kết không dùng được',
  'inactive.body': 'Liên kết đã hết hạn hoặc không dùng được. Vui lòng nhờ quản lý gửi lại.',
  'submitted.title': 'Hợp đồng đã được nộp',
  'submitted.body': 'Hợp đồng đã được nộp nên không thể mở lại. Bạn có thể đóng cửa sổ này.',
  'err.locked': 'Nhập sai {n} lần nên liên kết đã bị khóa. Vui lòng nhờ quản lý gửi lại.',
  'err.birthMismatch': 'Ngày sinh không khớp. Còn {n} lần thử.',
  'err.cookieExpired': 'Phiên xác minh đã hết hạn. Hãy tải lại trang và nhập lại ngày sinh.',
  'err.badRequest': 'Yêu cầu không hợp lệ.',
  'err.badImage': 'Hình chữ ký không hợp lệ.',
  'err.imageTooLarge': 'Hình chữ ký quá lớn. Vui lòng ký lại.',
  'err.disposalOff': 'Cơ sở này không dùng giấy đồng ý xử lý đồ đạc để lại.',
  'err.saveFail': 'Lưu chữ ký thất bại. Vui lòng thử lại sau giây lát.',
  'err.signFirst': 'Vui lòng ký xong trước.',
  'err.disposalLeft': 'Giấy đồng ý chưa được ký. Hãy ký vào giấy đồng ý rồi nộp.',
  'err.docLeft': "'{title}' chưa được ký. Hãy ký vào giấy tờ đó rồi nộp.",
  'err.submitFail': 'Nộp thất bại. Vui lòng thử lại sau giây lát.',
  'bar.readAndSign': 'Đọc nội dung hợp đồng, sau đó bấm vào ô chữ ký ở cuối trang để ký.',
  'bar.allSaved': 'Tất cả chữ ký đã được lưu. Hãy nộp bằng nút bên dưới.',
  'cta.sign': 'Bấm vào đây để ký',
  'progress.done1': 'Đã ký xong.',
  'progress.doneN': 'Đã ký {total} / {total}. Hoàn tất.',
  'progress.none1': 'Vui lòng ký tên.',
  'progress.noneN': 'Đã ký 0 / {total}. Vui lòng ký cả {total} chỗ.',
  'progress.some': 'Đã ký {n} / {total}. Còn {left} chỗ.',
  'cta.submit': 'Nộp',
  'cta.submitting': 'Đang nộp…',
  'pill.allDone': 'Đã ký xong tất cả',
  'pad.titleContract': 'Chữ ký người thuê',
  'pad.titleDoc': 'Chữ ký {title}',
  'pad.subRemote': 'Ký vào vùng bên dưới. Bấm Xác nhận để áp dụng chữ ký vào {title}.',
  'pad.clear': 'Xóa',
  'pad.cancel': 'Hủy',
  'pad.confirm': 'Xác nhận',
  'pad.saving': 'Đang lưu…',
  'pad.close': 'Đóng',
  'pad.errEmpty': 'Vui lòng ký tên.',
  'pad.errShort': 'Chữ ký quá ngắn. Vui lòng ký đầy đủ tên của bạn.',
  'pad.errComm': 'Lỗi mạng khi lưu chữ ký. Vui lòng thử lại sau giây lát.',
  'toast.signedContract': 'Đã nhận chữ ký',
  'toast.signedDoc': 'Đã nhận chữ ký {title}',
  'remain.title1': 'Đã ký {n} / {total}. Còn lại: {title}',
  'remain.titleN': 'Đã ký {n} / {total}. Còn {left} giấy tờ',
  'remain.msg': 'Liên kết này có {total} giấy tờ. Hãy ký {left} giấy tờ còn lại để nộp.',
  'remain.go': 'Đi đến chỗ ký',
  'submit.confirmTitle': 'Nộp hợp đồng?',
  'submit.confirmMsg': 'Sau khi nộp, liên kết này sẽ đóng và không thể mở lại hay sửa.\nNếu muốn sửa chữ ký, hãy ký lại trước khi nộp.',
  'submit.confirmLabel': 'Nộp',
  'submit.errComm': 'Lỗi mạng khi nộp. Vui lòng thử lại sau giây lát.',
  'done.title': 'Hợp đồng đã được nộp',
  'done.body': 'Liên kết này đã đóng và không thể mở lại. Bạn có thể đóng cửa sổ này.',
  'native.label': 'Tên theo tiếng mẹ đẻ',
  'native.required': 'Vui lòng viết tên bằng tiếng mẹ đẻ. Tên này sẽ hiện cạnh tên bạn trên hợp đồng.',
  'native.hint': 'Viết tên đúng như trong hộ chiếu hoặc giấy tờ của nước bạn.',
  'doc.contract': 'Hợp đồng thuê phòng',
  'doc.disposal': 'Giấy đồng ý',
  'doc.generic': 'Giấy tờ',
  'common.cancel': 'Hủy',
  'sms.body': '[{biz}] Hợp đồng thuê phòng của bạn. Mở liên kết bên dưới để đọc và ký. Cần nhập ngày sinh để xác minh. Liên kết sẽ đóng sau khi nộp và hết hạn sau 24 giờ.',
}

const BN: Record<SignKey, string> = {
  'gate.title': 'রুম চুক্তি যাচাই',
  'gate.hint': 'পরিচয় যাচাইয়ের জন্য আপনার জন্মতারিখ লিখুন। যাচাইয়ের পর চুক্তি পড়ে সই করতে পারবেন।',
  'gate.birthLabel': 'জন্মতারিখ',
  'gate.placeholder': 'যেমন: 19700928',
  'gate.submit': 'নিশ্চিত করুন',
  'gate.submitting': 'যাচাই চলছে…',
  'gate.netFail': 'যাচাই ব্যর্থ হয়েছে। একটু পরে আবার চেষ্টা করুন।',
  'gate.privacy': 'আপনার জন্মতারিখ শুধু পরিচয় যাচাইয়ে ব্যবহৃত হয়, সংরক্ষণ করা হয় না। চুক্তিতে লেখা তথ্য চুক্তি সম্পাদনের জন্য প্রতিষ্ঠান সংরক্ষণ করে।',
  'inactive.title': 'লিংকটি ব্যবহারযোগ্য নয়',
  'inactive.body': 'লিংকের মেয়াদ শেষ বা ব্যবহারযোগ্য নয়। ম্যানেজারকে আবার পাঠাতে বলুন।',
  'submitted.title': 'চুক্তি জমা হয়েছে',
  'submitted.body': 'ইতিমধ্যে জমা হয়ে গেছে, আর খোলা যাবে না। এই উইন্ডোটি বন্ধ করতে পারেন।',
  'err.locked': '{n} বার ভুল হওয়ায় লিংকটি লক হয়েছে। ম্যানেজারকে আবার পাঠাতে বলুন।',
  'err.birthMismatch': 'জন্মতারিখ মিলছে না। আর {n} বার চেষ্টা করা যাবে।',
  'err.cookieExpired': 'পরিচয় যাচাইয়ের মেয়াদ শেষ। পেজ রিফ্রেশ করে জন্মতারিখ আবার লিখুন।',
  'err.badRequest': 'ভুল অনুরোধ।',
  'err.badImage': 'সইয়ের ছবি সঠিক নয়।',
  'err.imageTooLarge': 'সইয়ের ছবি খুব বড়। আবার সই করুন।',
  'err.disposalOff': 'এই প্রতিষ্ঠান ফেলে যাওয়া জিনিস বিষয়ক সম্মতিপত্র ব্যবহার করে না।',
  'err.saveFail': 'সই সংরক্ষণ ব্যর্থ হয়েছে। একটু পরে আবার চেষ্টা করুন।',
  'err.signFirst': 'আগে সই সম্পূর্ণ করুন।',
  'err.disposalLeft': 'সম্মতিপত্রে এখনো সই হয়নি। সই করে তারপর জমা দিন।',
  'err.docLeft': "'{title}' এ এখনো সই হয়নি। সেই কাগজে সই করে জমা দিন।",
  'err.submitFail': 'জমা ব্যর্থ হয়েছে। একটু পরে আবার চেষ্টা করুন।',
  'bar.readAndSign': 'চুক্তি পড়ে নিচের সইয়ের ঘরে চাপ দিয়ে সই করুন।',
  'bar.allSaved': 'সব সই সংরক্ষিত হয়েছে। নিচের বোতাম দিয়ে জমা দিন।',
  'cta.sign': 'সই করতে এখানে চাপুন',
  'progress.done1': 'সই সম্পন্ন হয়েছে।',
  'progress.doneN': '{total} / {total} সই হয়েছে। সব শেষ।',
  'progress.none1': 'সই করুন।',
  'progress.noneN': '0 / {total} সই হয়েছে। {total} জায়গায় সই করুন।',
  'progress.some': '{n} / {total} সই হয়েছে। বাকি {left}।',
  'cta.submit': 'জমা দিন',
  'cta.submitting': 'জমা হচ্ছে…',
  'pill.allDone': 'সব সই সম্পন্ন',
  'pad.titleContract': 'ভাড়াটিয়ার সই',
  'pad.titleDoc': '{title} সই',
  'pad.subRemote': 'নিচের ঘরে সই করুন। নিশ্চিত চাপলে {title} এ সই বসবে।',
  'pad.clear': 'মুছুন',
  'pad.cancel': 'বাতিল',
  'pad.confirm': 'নিশ্চিত',
  'pad.saving': 'সংরক্ষণ হচ্ছে…',
  'pad.close': 'বন্ধ',
  'pad.errEmpty': 'সই করুন।',
  'pad.errShort': 'সই খুব ছোট। আপনার পুরো নাম টেনে সই করুন।',
  'pad.errComm': 'সই সংরক্ষণে নেটওয়ার্ক ত্রুটি। একটু পরে আবার চেষ্টা করুন।',
  'toast.signedContract': 'সই যোগ হয়েছে',
  'toast.signedDoc': '{title} সই যোগ হয়েছে',
  'remain.title1': '{n} / {total} সই হয়েছে। বাকি: {title}',
  'remain.titleN': '{n} / {total} সই হয়েছে। বাকি {left}টি কাগজ',
  'remain.msg': 'এই লিংকে {total}টি কাগজ আছে। বাকি {left}টিতে সই করলে জমা দেওয়া যাবে।',
  'remain.go': 'সইয়ের জায়গায় যান',
  'submit.confirmTitle': 'চুক্তি জমা দেবেন?',
  'submit.confirmMsg': 'জমা দিলে এই লিংক বন্ধ হবে। আর খোলা বা বদলানো যাবে না।\nসই বদলাতে চাইলে জমার আগে আবার সই করুন।',
  'submit.confirmLabel': 'জমা দিন',
  'submit.errComm': 'জমা দিতে নেটওয়ার্ক ত্রুটি। একটু পরে আবার চেষ্টা করুন।',
  'done.title': 'চুক্তি জমা হয়েছে',
  'done.body': 'এই লিংক বন্ধ হয়ে গেছে, আর খোলা যাবে না। এই উইন্ডোটি বন্ধ করতে পারেন।',
  'native.label': 'নিজ ভাষায় নাম',
  'native.required': 'নিজ ভাষায় আপনার নাম লিখুন। চুক্তিতে আপনার নামের পাশে ছাপা হবে।',
  'native.hint': 'পাসপোর্ট বা নিজ দেশের কাগজে যেমন লেখা তেমনই লিখুন।',
  'doc.contract': 'রুম চুক্তি',
  'doc.disposal': 'সম্মতিপত্র',
  'doc.generic': 'কাগজ',
  'common.cancel': 'বাতিল',
  'sms.body': '[{biz}] আপনার রুম চুক্তি। নিচের লিংক খুলে পড়ে সই করুন। যাচাইয়ের জন্য জন্মতারিখ লাগবে। জমার পর লিংক বন্ধ হবে, না দিলেও 24 ঘণ্টা পর মেয়াদ শেষ।',
}

const RU: Record<SignKey, string> = {
  'gate.title': 'Проверка договора аренды',
  'gate.hint': 'Введите дату рождения для подтверждения личности. После проверки вы сможете прочитать и подписать договор.',
  'gate.birthLabel': 'Дата рождения',
  'gate.placeholder': 'Например: 19700928',
  'gate.submit': 'Подтвердить',
  'gate.submitting': 'Проверка…',
  'gate.netFail': 'Не удалось проверить. Попробуйте еще раз чуть позже.',
  'gate.privacy': 'Дата рождения используется только для проверки личности и не сохраняется. Данные в договоре хранятся заведением для заключения и исполнения договора.',
  'inactive.title': 'Ссылка недоступна',
  'inactive.body': 'Ссылка истекла или недоступна. Попросите администратора отправить ее заново.',
  'submitted.title': 'Договор отправлен',
  'submitted.body': 'Договор уже отправлен и больше не открывается. Это окно можно закрыть.',
  'err.locked': 'Ссылка заблокирована после {n} неверных попыток. Попросите администратора отправить ее заново.',
  'err.birthMismatch': 'Дата рождения не совпадает. Осталось попыток: {n}.',
  'err.cookieExpired': 'Проверка личности истекла. Обновите страницу и введите дату рождения заново.',
  'err.badRequest': 'Неверный запрос.',
  'err.badImage': 'Изображение подписи некорректно.',
  'err.imageTooLarge': 'Изображение подписи слишком большое. Подпишите заново.',
  'err.disposalOff': 'Это заведение не использует согласие об оставленных вещах.',
  'err.saveFail': 'Не удалось сохранить подпись. Попробуйте еще раз чуть позже.',
  'err.signFirst': 'Сначала поставьте подпись.',
  'err.disposalLeft': 'Согласие еще не подписано. Подпишите его перед отправкой.',
  'err.docLeft': "Документ '{title}' еще не подписан. Подпишите его перед отправкой.",
  'err.submitFail': 'Не удалось отправить. Попробуйте еще раз чуть позже.',
  'bar.readAndSign': 'Прочитайте договор и нажмите на поле подписи внизу, чтобы подписать.',
  'bar.allSaved': 'Все подписи сохранены. Отправьте кнопкой ниже.',
  'cta.sign': 'Нажмите здесь, чтобы подписать',
  'progress.done1': 'Подписано.',
  'progress.doneN': 'Подписано {total} / {total}. Готово.',
  'progress.none1': 'Пожалуйста, подпишите.',
  'progress.noneN': 'Подписано 0 / {total}. Подпишите все {total}.',
  'progress.some': 'Подписано {n} / {total}. Осталось {left}.',
  'cta.submit': 'Отправить',
  'cta.submitting': 'Отправка…',
  'pill.allDone': 'Все подписи поставлены',
  'pad.titleContract': 'Подпись жильца',
  'pad.titleDoc': 'Подпись: {title}',
  'pad.subRemote': 'Распишитесь в поле ниже. Нажмите Подтвердить, чтобы применить подпись к документу {title}.',
  'pad.clear': 'Стереть',
  'pad.cancel': 'Отмена',
  'pad.confirm': 'Подтвердить',
  'pad.saving': 'Сохранение…',
  'pad.close': 'Закрыть',
  'pad.errEmpty': 'Пожалуйста, распишитесь.',
  'pad.errShort': 'Подпись слишком короткая. Распишитесь полностью.',
  'pad.errComm': 'Сетевая ошибка при сохранении подписи. Попробуйте еще раз чуть позже.',
  'toast.signedContract': 'Подпись добавлена',
  'toast.signedDoc': 'Подпись добавлена: {title}',
  'remain.title1': 'Подписано {n} / {total}. Осталось: {title}',
  'remain.titleN': 'Подписано {n} / {total}. Осталось документов: {left}',
  'remain.msg': 'В этой ссылке {total} документа(ов). Подпишите оставшиеся {left}, чтобы отправить.',
  'remain.go': 'Перейти к подписи',
  'submit.confirmTitle': 'Отправить договор?',
  'submit.confirmMsg': 'После отправки ссылка закроется. Открыть или изменить ее будет нельзя.\nЧтобы изменить подпись, распишитесь заново до отправки.',
  'submit.confirmLabel': 'Отправить',
  'submit.errComm': 'Сетевая ошибка при отправке. Попробуйте еще раз чуть позже.',
  'done.title': 'Договор отправлен',
  'done.body': 'Ссылка закрыта и больше не открывается. Это окно можно закрыть.',
  'native.label': 'Имя на родном языке',
  'native.required': 'Пожалуйста, напишите имя на родном языке. Оно появится рядом с вашим именем в договоре.',
  'native.hint': 'Напишите имя так, как в паспорте или документах вашей страны.',
  'doc.contract': 'Договор аренды',
  'doc.disposal': 'Согласие',
  'doc.generic': 'Документ',
  'common.cancel': 'Отмена',
  'sms.body': '[{biz}] Ваш договор аренды. Откройте ссылку ниже, прочитайте и подпишите. Для проверки понадобится дата рождения. После отправки ссылка закроется, срок действия 24 часа.',
}

const JA: Record<SignKey, string> = {
  'gate.title': '入室契約書の確認',
  'gate.hint': '本人確認のため生年月日を入力してください。確認後、契約内容を読んで署名できます。',
  'gate.birthLabel': '生年月日',
  'gate.placeholder': '例: 19700928',
  'gate.submit': '確認',
  'gate.submitting': '確認中…',
  'gate.netFail': '確認に失敗しました。しばらくしてからもう一度お試しください。',
  'gate.privacy': '入力された生年月日は本人確認のみに使用し、保存しません。契約書の情報は契約の締結と履行のため施設が保管します。',
  'inactive.title': '使用できないリンク',
  'inactive.body': 'リンクの有効期限が切れているか使用できません。管理者に再送を依頼してください。',
  'submitted.title': '契約書が提出されました',
  'submitted.body': 'すでに提出が完了しているため開けません。このウィンドウは閉じて構いません。',
  'err.locked': '入力を{n}回間違えたためリンクがロックされました。管理者に再送を依頼してください。',
  'err.birthMismatch': '生年月日が一致しません。残り{n}回。',
  'err.cookieExpired': '本人確認の有効期限が切れました。ページを更新して生年月日をもう一度入力してください。',
  'err.badRequest': '不正なリクエストです。',
  'err.badImage': '署名画像が正しくありません。',
  'err.imageTooLarge': '署名画像が大きすぎます。もう一度署名してください。',
  'err.disposalOff': 'この施設は残置物処分同意書を使用していません。',
  'err.saveFail': '署名の保存に失敗しました。しばらくしてからもう一度お試しください。',
  'err.signFirst': '先に署名を完了してください。',
  'err.disposalLeft': '同意書がまだ署名されていません。署名してから提出してください。',
  'err.docLeft': '「{title}」がまだ署名されていません。その書類に署名してから提出してください。',
  'err.submitFail': '提出に失敗しました。しばらくしてからもう一度お試しください。',
  'bar.readAndSign': '契約内容を確認して、下の署名欄を押して署名してください。',
  'bar.allSaved': '署名がすべて保存されました。下のボタンで提出してください。',
  'cta.sign': 'ここを押して署名',
  'progress.done1': '署名が完了しました。',
  'progress.doneN': '署名 {total} / {total}。すべて完了しました。',
  'progress.none1': '署名してください。',
  'progress.noneN': '署名 0 / {total}。{total}か所に署名してください。',
  'progress.some': '署名 {n} / {total}。残り{left}か所。',
  'cta.submit': '提出する',
  'cta.submitting': '提出中…',
  'pill.allDone': 'すべての署名が完了しました',
  'pad.titleContract': '入室者署名',
  'pad.titleDoc': '{title}の署名',
  'pad.subRemote': '下の枠内に署名してください。確認を押すと{title}に署名が適用されます。',
  'pad.clear': '消す',
  'pad.cancel': 'キャンセル',
  'pad.confirm': '確認',
  'pad.saving': '保存中…',
  'pad.close': '閉じる',
  'pad.errEmpty': '署名を入力してください。',
  'pad.errShort': '署名が短すぎます。名前を続けて書いてください。',
  'pad.errComm': '署名保存中に通信エラーが発生しました。しばらくしてからもう一度お試しください。',
  'toast.signedContract': '署名が入力されました',
  'toast.signedDoc': '{title}の署名が入力されました',
  'remain.title1': '署名 {n} / {total}。残り: {title}',
  'remain.titleN': '署名 {n} / {total}。残り{left}枚',
  'remain.msg': 'このリンクには書類が{total}枚あります。残り{left}枚に署名すると提出できます。',
  'remain.go': '署名しに行く',
  'submit.confirmTitle': '契約書を提出しますか?',
  'submit.confirmMsg': '提出するとこのリンクは閉じます。再び開いたり修正したりできません。\n署名を直す場合は提出前にもう一度署名してください。',
  'submit.confirmLabel': '提出',
  'submit.errComm': '提出中に通信エラーが発生しました。しばらくしてからもう一度お試しください。',
  'done.title': '契約書が提出されました',
  'done.body': 'このリンクは閉じられ、再び開けません。このウィンドウは閉じて構いません。',
  'native.label': '母国語表記の氏名',
  'native.required': '母国語表記の氏名を書いてください。契約書の氏名の横に載ります。',
  'native.hint': 'パスポートや母国の書類に書かれている通りに書いてください。',
  'doc.contract': '入室契約書',
  'doc.disposal': '同意書',
  'doc.generic': '書類',
  'common.cancel': 'キャンセル',
  'sms.body': '[{biz}] 入室契約書です。下のリンクから内容を確認して署名してください。確認のため生年月日の入力が必要です。提出するとリンクは閉じ、未提出でも24時間後に期限切れになります。',
}

const ZH: Record<SignKey, string> = {
  'gate.title': '入住合同确认',
  'gate.hint': '请输入出生日期以验证身份。验证后即可阅读并签署合同。',
  'gate.birthLabel': '出生日期',
  'gate.placeholder': '例: 19700928',
  'gate.submit': '确认',
  'gate.submitting': '验证中…',
  'gate.netFail': '验证失败。请稍后再试。',
  'gate.privacy': '您输入的出生日期仅用于身份验证,不会被保存。合同中的信息由经营方保管,用于签订和履行合同。',
  'inactive.title': '链接不可用',
  'inactive.body': '链接已过期或不可用。请联系管理员重新发送。',
  'submitted.title': '合同已提交',
  'submitted.body': '已提交完成,无法再次打开。您可以关闭此窗口。',
  'err.locked': '输入错误{n}次,链接已锁定。请联系管理员重新发送。',
  'err.birthMismatch': '出生日期不一致。剩余{n}次机会。',
  'err.cookieExpired': '身份验证已过期。请刷新页面并重新输入出生日期。',
  'err.badRequest': '无效的请求。',
  'err.badImage': '签名图像无效。',
  'err.imageTooLarge': '签名图像过大。请重新签名。',
  'err.disposalOff': '本店不使用遗留物品处理同意书。',
  'err.saveFail': '签名保存失败。请稍后再试。',
  'err.signFirst': '请先完成签名。',
  'err.disposalLeft': '同意书尚未签名。请先在同意书上签名再提交。',
  'err.docLeft': "'{title}'尚未签名。请先在该文件上签名再提交。",
  'err.submitFail': '提交失败。请稍后再试。',
  'bar.readAndSign': '请阅读合同内容,然后点击底部的签名栏进行签名。',
  'bar.allSaved': '所有签名已保存。请用下方按钮提交。',
  'cta.sign': '点击此处签名',
  'progress.done1': '签名已完成。',
  'progress.doneN': '已签 {total} / {total}。全部完成。',
  'progress.none1': '请签名。',
  'progress.noneN': '已签 0 / {total}。请在{total}处签名。',
  'progress.some': '已签 {n} / {total}。还剩{left}处。',
  'cta.submit': '提交',
  'cta.submitting': '提交中…',
  'pill.allDone': '所有签名已完成',
  'pad.titleContract': '入住人签名',
  'pad.titleDoc': '{title}签名',
  'pad.subRemote': '请在下方区域签名。点击确认后,签名将应用到{title}。',
  'pad.clear': '清除',
  'pad.cancel': '取消',
  'pad.confirm': '确认',
  'pad.saving': '保存中…',
  'pad.close': '关闭',
  'pad.errEmpty': '请签名。',
  'pad.errShort': '签名太短。请连笔写出您的姓名。',
  'pad.errComm': '保存签名时发生网络错误。请稍后再试。',
  'toast.signedContract': '签名已录入',
  'toast.signedDoc': '{title}签名已录入',
  'remain.title1': '已签 {n} / {total}。还剩: {title}',
  'remain.titleN': '已签 {n} / {total}。还剩{left}份文件',
  'remain.msg': '此链接共有{total}份文件。签完剩余{left}份即可提交。',
  'remain.go': '前往签名',
  'submit.confirmTitle': '提交合同吗?',
  'submit.confirmMsg': '提交后此链接将关闭,无法再次打开或修改。\n如需修改签名,请在提交前重新签名。',
  'submit.confirmLabel': '提交',
  'submit.errComm': '提交时发生网络错误。请稍后再试。',
  'done.title': '合同已提交',
  'done.body': '此链接已关闭,无法再次打开。您可以关闭此窗口。',
  'native.label': '母语姓名',
  'native.required': '请填写母语姓名。它将显示在合同姓名旁边。',
  'native.hint': '请按护照或本国证件上的写法填写。',
  'doc.contract': '入住合同',
  'doc.disposal': '同意书',
  'doc.generic': '文件',
  'common.cancel': '取消',
  'sms.body': '[{biz}] 您的入住合同。请打开下方链接阅读并签名。验证需要输入出生日期。提交后链接将关闭,未提交也将在24小时后过期。',
}


const ZHT: Record<SignKey, string> = {
  'gate.title': '入住合約確認',
  'gate.hint': '請輸入出生日期以驗證身分。驗證後即可閱讀並簽署合約。',
  'gate.birthLabel': '出生日期',
  'gate.placeholder': '例: 19700928',
  'gate.submit': '確認',
  'gate.submitting': '驗證中…',
  'gate.netFail': '驗證失敗。請稍後再試。',
  'gate.privacy': '您輸入的出生日期僅用於身分驗證,不會被保存。合約中的資訊由經營方保管,用於簽訂與履行合約。',
  'inactive.title': '連結無法使用',
  'inactive.body': '連結已過期或無法使用。請聯絡管理員重新發送。',
  'submitted.title': '合約已提交',
  'submitted.body': '已完成提交,無法再次開啟。您可以關閉此視窗。',
  'err.locked': '輸入錯誤{n}次,連結已鎖定。請聯絡管理員重新發送。',
  'err.birthMismatch': '出生日期不一致。剩餘{n}次機會。',
  'err.cookieExpired': '身分驗證已過期。請重新整理頁面並再次輸入出生日期。',
  'err.badRequest': '無效的請求。',
  'err.badImage': '簽名圖像無效。',
  'err.imageTooLarge': '簽名圖像過大。請重新簽名。',
  'err.disposalOff': '本店不使用遺留物品處理同意書。',
  'err.saveFail': '簽名儲存失敗。請稍後再試。',
  'err.signFirst': '請先完成簽名。',
  'err.disposalLeft': '同意書尚未簽名。請先在同意書上簽名再提交。',
  'err.docLeft': "'{title}'尚未簽名。請先在該文件上簽名再提交。",
  'err.submitFail': '提交失敗。請稍後再試。',
  'bar.readAndSign': '請閱讀合約內容,然後點擊底部的簽名欄進行簽名。',
  'bar.allSaved': '所有簽名已儲存。請用下方按鈕提交。',
  'cta.sign': '點擊此處簽名',
  'progress.done1': '簽名已完成。',
  'progress.doneN': '已簽 {total} / {total}。全部完成。',
  'progress.none1': '請簽名。',
  'progress.noneN': '已簽 0 / {total}。請在{total}處簽名。',
  'progress.some': '已簽 {n} / {total}。還剩{left}處。',
  'cta.submit': '提交',
  'cta.submitting': '提交中…',
  'pill.allDone': '所有簽名已完成',
  'pad.titleContract': '入住人簽名',
  'pad.titleDoc': '{title}簽名',
  'pad.subRemote': '請在下方區域簽名。點擊確認後,簽名將套用到{title}。',
  'pad.clear': '清除',
  'pad.cancel': '取消',
  'pad.confirm': '確認',
  'pad.saving': '儲存中…',
  'pad.close': '關閉',
  'pad.errEmpty': '請簽名。',
  'pad.errShort': '簽名太短。請連筆寫出您的姓名。',
  'pad.errComm': '儲存簽名時發生網路錯誤。請稍後再試。',
  'toast.signedContract': '簽名已錄入',
  'toast.signedDoc': '{title}簽名已錄入',
  'remain.title1': '已簽 {n} / {total}。還剩: {title}',
  'remain.titleN': '已簽 {n} / {total}。還剩{left}份文件',
  'remain.msg': '此連結共有{total}份文件。簽完剩餘{left}份即可提交。',
  'remain.go': '前往簽名',
  'submit.confirmTitle': '提交合約嗎?',
  'submit.confirmMsg': '提交後此連結將關閉,無法再次開啟或修改。\n如需修改簽名,請在提交前重新簽名。',
  'submit.confirmLabel': '提交',
  'submit.errComm': '提交時發生網路錯誤。請稍後再試。',
  'done.title': '合約已提交',
  'done.body': '此連結已關閉,無法再次開啟。您可以關閉此視窗。',
  'native.label': '母語姓名',
  'native.required': '請填寫母語姓名。它將顯示在合約姓名旁邊。',
  'native.hint': '請按照護照或本國證件上的寫法填寫。',
  'doc.contract': '入住合約',
  'doc.disposal': '同意書',
  'doc.generic': '文件',
  'common.cancel': '取消',
  'sms.body': '[{biz}] 您的入住合約。請開啟下方連結閱讀並簽名。驗證需要輸入出生日期。提交後連結將關閉,未提交也將於24小時後過期。',
}

const DICT: Record<SignLang, Record<SignKey, string>> = { ko: KO, en: EN, vi: VI, bn: BN, ru: RU, ja: JA, zh: ZH, zht: ZHT }

function fill(s: string, vars?: Record<string, string | number>): string {
  if (!vars) return s
  return s.replace(/\{(\w+)\}/g, (m, k) => (k in vars ? String(vars[k]) : m))
}

/** 한 언어의 문장. 폴백 사슬(en, ko)은 타입 우회에 대한 안전벨트일 뿐이다 — 정상 경로에선 안 탄다. */
export function t(lang: SignLang, key: SignKey, vars?: Record<string, string | number>): string {
  return fill(DICT[lang]?.[key] ?? DICT.en[key] ?? KO[key], vars)
}

/** 부속 줄의 언어. 한국어를 골랐으면 영어다 — 부속 줄은 원격이면 언제나 선다. */
export function subLangOf(lang: SignLang): Exclude<SignLang, 'ko'> {
  return lang === 'ko' ? 'en' : lang
}

/**
 * 병기 문장 — 한국어 정본 줄 + 선택 언어 부속 줄.
 *
 * 항상 한국어 줄이 앞선다. 운영자가 전화로 같은 화면을 읽으며 안내할 수 있어야 하고,
 * 분쟁 시 "무엇을 안내받았나"의 정본이 한국어로 남아야 하며, humanError 가 한글 없는
 * 문자열을 폴백으로 갈아치우기 때문이다(lib/saveStatus).
 */
export function bi(lang: SignLang, key: SignKey, vars?: Record<string, string | number>): string {
  return `${t('ko', key, vars)}\n${t(subLangOf(lang), key, vars)}`
}

/**
 * 서명 요청 문자 본문. 한국어를 골랐으면 종전 문자와 글자 하나까지 같다.
 * 외국어면 그 언어 문장이 먼저 서고(받는 사람이 첫 줄에서 제 언어를 본다), 한국어 정본이
 * 그 아래, URL 은 맨 끝에 한 번 붙는다.
 */
export function smsBodyFor(lang: SignLang, biz: string, url: string): string {
  if (lang === 'ko') return `${t('ko', 'sms.body', { biz })} ${url}`
  return `${t(lang, 'sms.body', { biz })}\n${t('ko', 'sms.body', { biz })}\n${url}`
}

/** 병기를 한 줄로 — 버튼처럼 줄바꿈이 안 어울리는 좁은 자리용. 한국어를 골랐으면 한국어만. */
export function biLine(lang: SignLang, key: SignKey, vars?: Record<string, string | number>): string {
  if (lang === 'ko') return t('ko', key, vars)
  return `${t('ko', key, vars)} · ${t(lang, key, vars)}`
}
